// SPDX-FileCopyrightText: 2023 Industria de Diseño Textil S.A. INDITEX
//
// SPDX-License-Identifier: Apache-2.0

/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "intellijhub"
